# Generated by Django 3.1.14 on 2022-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_auto_20220706_1635'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(condition=models.Q(is_default=True), fields=('is_default',), name='unique_default'),
        ),
    ]
