# Generated by Django 4.2.11 on 2024-10-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_auto_20230223_0008'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='package',
            name='unique_default',
        ),
    ]
